server:
  port: 8080

spring:
  application:
    name: api-gateway-quickbite

  cloud:
    gateway:
      server:
        webmvc:
          routes:

            # AUTH SERVICE
            - id: auth-service
              uri: http://localhost:8081
              predicates:
                - Path=/api/auth/**

            # USER SERVICE (Rutas separadas explícitamente para evitar fallos en WebMVC)
            - id: user-service-en
              uri: http://localhost:8082
              predicates:
                - Path=/api/users/**
            - id: user-service-es
              uri: http://localhost:8082
              predicates:
                - Path=/api/usuarios/**

            # MENU SERVICE (Rutas separadas explícitamente para evitar fallos en WebMVC)
            - id: menu-service-main
              uri: http://localhost:8083
              predicates:
                - Path=/api/menu/**
            - id: menu-service-categories
              uri: http://localhost:8083
              predicates:
                - Path=/api/categorias/**
            - id: menu-service-products
              uri: http://localhost:8083
              predicates:
                - Path=/api/productos/**

            # ORDER SERVICE
            - id: order-service-quickbite
              uri: http://localhost:8084
              predicates:
                - Path=/api/ordenes/**

            # PAYMENTS SERVICE
            - id: pagos-service
              uri: http://localhost:8085
              predicates:
                - Path=/api/pagos/**

            # NOTIFICATION SERVICE
            - id: notification-service
              uri: http://localhost:8086
              predicates:
                - Path=/api/notificaciones/**

            # SWAGGER AUTH
            - id: auth-docs
              uri: http://localhost:8081
              predicates:
                - Path=/auth-docs

            # SWAGGER USER
            - id: user-docs
              uri: http://localhost:8082
              predicates:
                - Path=/user-docs

            # SWAGGER MENU
            - id: menu-docs
              uri: http://localhost:8083
              predicates:
                - Path=/menu-docs

            # SWAGGER ORDER
            - id: order-docs
              uri: http://localhost:8084
              predicates:
                - Path=/order-docs

            # SWAGGER PAYMENT
            - id: payment-docs
              uri: http://localhost:8085
              predicates:
                - Path=/payment-docs

            # SWAGGER NOTIFICATION
            - id: notification-docs
              uri: http://localhost:8086
              predicates:
                - Path=/notification-docs

management:
  endpoints:
    web:
      exposure:
        include: health,info